name: giphy_api_client
description: A Giphy API Client for Dart compatible Web, Flutter, and server-side dart
version: 0.1.3
homepage: https://github.com/java-james/giphy_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.2.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: 2.1.7
  coverage: 1.1.0
  lints: ^1.0.1
  mockito: 5.1.0
  test: 1.20.1
